CREATE TABLE users (
                       user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                       user_name VARCHAR(255) NOT NULL,
                       user_email VARCHAR(255) NOT NULL UNIQUE,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE authors
(
    author_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name    VARCHAR(255) NOT NULL,
    author_surname VARCHAR(255) NOT NULL
);

CREATE TABLE books
(
    book_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name        VARCHAR(255) NOT NULL,
    book_description VARCHAR(255) NOT NULL,
    author_id        BIGINT,
    FOREIGN KEY (author_id) REFERENCES authors (author_id) ON DELETE SET NULL
);
