CREATE TABLE IF NOT EXISTS authors
(
    author_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_name    VARCHAR(255)                            NOT NULL,
    author_surname VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS books
(
    book_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_name        VARCHAR(255)                            NOT NULL,
    book_description VARCHAR(255)                            NOT NULL,
    author_id        BIGINT,
    CONSTRAINT pk_books PRIMARY KEY (book_id)
);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (author_id);